api:
  image: incriszz/taskflow-api:v1
  replicas: 2
frontend:
  image: incriszz/taskflow-frontend:v1
  replicas: 2
postgres:
  image: postgres:17-alpine
  storage: 2Gi
redis:
  image: redis:7-alpine
existingSecret: taskflow-secret
config:
  databaseName: taskflow
imagePullPolicy: IfNotPresent
