apiVersion: rbac.authorization.k8s.io/v1
kind: Role

metadata:

  name: taskflow-developer

  namespace: taskflow


rules:

# Allow viewing Pods

- apiGroups:
  - ""

  resources:
  - pods

  verbs:
  - get
  - list
  - watch


# Allow viewing Services

- apiGroups:
  - ""

  resources:
  - services

  verbs:
  - get
  - list
  - watch


# Allow viewing Deployments

- apiGroups:
  - apps

  resources:
  - deployments

  verbs:
  - get
  - list
  - watch