apiVersion: apps/v1
kind: Deployment

metadata:
  name: taskflow-api
  namespace: taskflow


spec:

  replicas: 1

  selector:
    matchLabels:
      app: taskflow-api


  template:

    metadata:
      labels:
        app: taskflow-api


    spec:

      containers:

      - name: api

        image: incriszz/taskflow-api:latest


        ports:

        - containerPort: 5000


        envFrom:


        - configMapRef:
            name: taskflow-backend-config


        - secretRef:
            name: taskflow-backend-secret