
apiVersion: v1
kind: Service

metadata:

  name: taskflow-api

  namespace: taskflow


spec:

  type: NodePort


  selector:

    app: taskflow-api


  ports:

  - port: 5000
    targetPort: 5000
    nodePort: 30500
