apiVersion: apps/v1

kind: Deployment

metadata:

  name: taskflow-frontend

  namespace: taskflow


spec:

  replicas: 1


  selector:

    matchLabels:

      app: taskflow-frontend


  template:

    metadata:

      labels:

        app: taskflow-frontend


    spec:


      containers:

      - name: frontend

        image: incriszz/taskflow-frontend:v1


        ports:

        - containerPort: 80


        env:
        - name: API_URL
          valueFrom:
            configMapKeyRef:
              name: taskflow-frontend-config
              key: API_URL

        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
          readOnly: true

      volumes:
      - name: nginx-config
        configMap:
          name: taskflow-frontend-config
          items:
          - key: default.conf
            path: default.conf
