apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 00-namespace.yaml
  - 01-config/config.yaml
  - 02-rbac/rbac.yaml
  - 03-postgres/init-configmap.yaml
  - 03-postgres/postgres.yaml
  - 04-redis/redis.yaml
  - 05-backend/api.yaml
  - 06-frontend/frontend.yaml
