apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding


metadata:

  name: taskflow-developer-binding

  namespace: taskflow



subjects:

# User getting permission

- kind: User

  name: taskflow-developer

  apiGroup: rbac.authorization.k8s.io



roleRef:

  kind: Role

  name: taskflow-developer

  apiGroup: rbac.authorization.k8s.io