apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../kubernetes
  - nginx-config.yaml
  - disruption-budgets.yaml
  - network-policies.yaml
patches:
  - path: patches/api.yaml
  - path: patches/frontend.yaml
  - path: patches/postgres.yaml
  - path: patches/redis.yaml
  - path: patches/frontend-service.yaml
  - path: patches/namespace.yaml
  - path: patches/remove-api-binding.yaml
  - path: patches/external-secret.yaml
